// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrGoDIT_Ea9-_Asc7VKoZ_7dEhF2YLMng',
    appId: '1:874457674237:web:3178aef43c686e2c9fa994',
    messagingSenderId: '874457674237',
    projectId: 'tcs-paceport-scheduler',
    authDomain: 'tcs-paceport-scheduler.firebaseapp.com',
    storageBucket: 'tcs-paceport-scheduler.firebasestorage.app',
    measurementId: 'G-S5WREPYEFX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAdV5i4g0Pr6FUPNVwrEFzoYHPuIEqPD0',
    appId: '1:874457674237:android:81596c5009b03f9a9fa994',
    messagingSenderId: '874457674237',
    projectId: 'tcs-paceport-scheduler',
    storageBucket: 'tcs-paceport-scheduler.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjsmf1IjvbtA4t18YjwGvObJR9Rztu2gY',
    appId: '1:874457674237:ios:705420cf66986a579fa994',
    messagingSenderId: '874457674237',
    projectId: 'tcs-paceport-scheduler',
    storageBucket: 'tcs-paceport-scheduler.firebasestorage.app',
    iosBundleId: 'com.example.flutterMultiplatformApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjsmf1IjvbtA4t18YjwGvObJR9Rztu2gY',
    appId: '1:874457674237:ios:705420cf66986a579fa994',
    messagingSenderId: '874457674237',
    projectId: 'tcs-paceport-scheduler',
    storageBucket: 'tcs-paceport-scheduler.firebasestorage.app',
    iosBundleId: 'com.example.flutterMultiplatformApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrGoDIT_Ea9-_Asc7VKoZ_7dEhF2YLMng',
    appId: '1:874457674237:web:3178aef43c686e2c9fa994',
    messagingSenderId: '874457674237',
    projectId: 'tcs-paceport-scheduler',
    authDomain: 'tcs-paceport-scheduler.firebaseapp.com',
    storageBucket: 'tcs-paceport-scheduler.firebasestorage.app',
    measurementId: 'G-S5WREPYEFX',
  );

}